
title: Tạp Nham Blog
author: Hứa Anh Minh
email: huaanhminh0412@gmail.com
description: >- 
  © 2017-2020 Tạp Nham Blog
baseurl: ""
url: https://tapnhamblog.github.io/ 
twitter_username: o0baragaki0o
github_username:  HuaAnhMinh
linkedin_username: minh-hứa-6808a6155

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  
include:
  - "_img"